### ISSUE TITLE
get zig working well on windows

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#302]
* [x] fix having to use workaround of specifying `--target` options in order to make tests work
 * [x] implement `___chkstk_ms`
 * [x] more than some number of output lines is cut off becase os.cpp has a bad implementation of spawning child process on windows
 * [x] behavior tests passing
 * [x] `pub main` or `export fn main` causes `-mconsole`, `export fn WinMain` causes `-mwindows`.
* [x] (bonus) don't depend on libc on windows
* [x] #463 standard library search path
* [ ] #516 ~exes generated with environment msvc should make pdb files and be debuggable with msvc~ 
* [x] add 32 bit windows as a test target and make that pass too
* [x] hello world libc working
 * [x] get zig building statically
* [x] tests passing on linux running cross compiled behavior tests with wine
* [x] compiler-rt tests passing
 * [x] fix compile error coloring in the terminal
* [x] panic does not print to stderr usefully
* [x] std lib tests passing
* [x] `std.io.InStream` windows implementation
* [x] `std.os.args` windows implementation
 * [x] `std.os.ChildProcess` windows implementation 
* [x] passing tests: test-behavior          Run the behavior tests
* [x] passing tests: test-std               Run the standard library tests
* [x] passing tests: test-compiler-rt       Run the compiler_rt tests
* [x] passing tests: test-compare-output    Run the compare output tests
* [x] passing tests: test-build-examples    Build the examples
* [x] passing tests: test-compile-errors    Run the compile error tests
* [x] passing tests: test-asm-link          Run the assemble and link tests
* [x] passing tests: test-debug-safety      Run the debug safety tests
* [x] passing tests: test-parsec            Run the C header file parsing tests
* [x] `.\bin\zig.exe --build-file ..\build.zig test` all passing
* [ ] #539 ~look for libc at runtime~
* [ ] ~cross compiling [tetris](https://github.com/andrewrk/tetris) using zig build system~
* [ ] ~native building of tetris~
* [ ] set up appveyor to run tests when commits pushed to master
* [ ] set up appveyor to provide build artifacts

**Comment by andrewrk** [comment]
There seems to be an issue with LLVM when using the native target features for my laptop. I sent [an email ](http://lists.llvm.org/pipermail/llvm-dev/2017-September/117860.html) to the llvm-dev mailing list. For now I will check for Windows OS and skip using the target native features as a workaround.

**Comment by andrewrk** [comment]
@marler8997 I'm doing a lot of windows work this weekend. Are you around?

**Comment by andrewrk** [comment]
I believe the remaining behavior test failure is an LLVM bug: http://lists.llvm.org/pipermail/llvm-dev/2017-September/117864.html

I think I can work around this by specifying extra alignment for packed structs.
